import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { test } from "node:test";

const indexHtml = await readFile(new URL("../app/index.html", import.meta.url), "utf8");
const appJs = await readFile(new URL("../app/app.js", import.meta.url), "utf8");
const mvpHtml = await readFile(new URL("../app/mvp.html", import.meta.url), "utf8");
const mvpJs = await readFile(new URL("../app/mvp.js", import.meta.url), "utf8");
const mvpCss = await readFile(new URL("../app/mvp.css", import.meta.url), "utf8");

test("chat MVP surface exposes guided auth, portal readiness, and runtime timeline", () => {
  assert.match(indexHtml, /id="chatJourney"/);
  assert.match(indexHtml, /id="portalReady"/);
  assert.match(indexHtml, /id="officialOpenClawCurrentTab"/);
  assert.match(indexHtml, /id="officialOpenClawMultiPage"/);
  assert.match(indexHtml, /id="resetMvpJourney"/);
  assert.match(indexHtml, /id="replayMvpBenefits"/);
  assert.match(indexHtml, /id="answerPanel"/);
  assert.match(indexHtml, /id="runtimeTimeline"/);
  assert.match(indexHtml, /id="loadRuntimeEvents"/);
  assert.match(indexHtml, /id="liveWorkerGuide"/);
  assert.match(indexHtml, /id="checkLiveWorker"/);
  assert.match(indexHtml, /id="liveWorkerStatus"/);
  assert.match(indexHtml, /id="workerVersatility"/);
  assert.match(indexHtml, /Runtime Timeline/);
  assert.match(indexHtml, /Use official OpenClaw worker/);
  assert.match(indexHtml, /Use current OpenClaw tab/);
  assert.match(indexHtml, /Multi-page read-only worker/);
  assert.match(indexHtml, /Live Worker Readiness/);
  assert.match(indexHtml, /Replay Benefits MVP/);
});

test("chat MVP JavaScript requires sign-in and renders runtime graph events", () => {
  assert.match(appJs, /requireSignedInBeforeWorkflow/);
  assert.match(appJs, /\/api\/runtime\/events\?sessionId=/);
  assert.match(appJs, /EventSource/);
  assert.match(appJs, /workflow\.classified/);
  assert.match(appJs, /worker\.plan\.prepared/);
  assert.match(appJs, /approval\.recorded/);
  assert.match(appJs, /approval\.consumed/);
  assert.match(appJs, /worker\.status\.updated/);
  assert.match(appJs, /llmDecision\.mode/);
  assert.match(appJs, /renderWorkerOutcomeCard/);
  assert.match(appJs, /friendlyWorkerBlocker/);
  assert.match(appJs, /structuredBenefitSummary/);
  assert.match(appJs, /structuredClaimSummary/);
  assert.match(appJs, /Structured claims/);
  assert.match(appJs, /Discovery/);
  assert.match(appJs, /discoverySummary/);
  assert.match(appJs, /renderDocumentCandidateProof/);
  assert.match(appJs, /data-document-candidate-propose/);
  assert.match(appJs, /data-document-candidate-observe/);
  assert.match(appJs, /Evidence channels/);
  assert.match(appJs, /renderLiveWorkerGuide/);
  assert.match(appJs, /liveReadiness/);
  assert.match(appJs, /ready_for_read_only_approval/);
  assert.match(appJs, /auth_required/);
  assert.match(appJs, /auth_or_challenge_required/);
  assert.match(appJs, /portal_page_required/);
  assert.match(appJs, /Worker may try after approval/);
  assert.match(appJs, /Always blocked/);
  assert.match(appJs, /Fallback chain/);
});

test("chat MVP exposes repeatable benefits replay and final answer surface", () => {
  assert.match(appJs, /MVP_BENEFITS_MESSAGE/);
  assert.match(appJs, /resetMvpJourneySurface/);
  assert.match(appJs, /replayMvpBenefitsJourney/);
  assert.match(appJs, /productAuthenticate/);
  assert.match(appJs, /runProductChat\(MVP_BENEFITS_MESSAGE\)/);
  assert.match(appJs, /renderAnswerPanel/);
  assert.match(appJs, /Current Answer/);
  assert.match(appJs, /Latest LangGraph result for this session/);
  assert.match(appJs, /latest-answer-message/);
  assert.match(appJs, /memoryRetainSummary/);
  assert.match(appJs, /memoryNextAction/);
  assert.match(appJs, /data-answer-approve-readonly/);
  assert.match(appJs, /data-answer-worker-followup/);
  assert.match(appJs, /\/api\/orchestrator\/auth-start/);
  assert.match(appJs, /\/api\/chat/);
});

test("chat MVP keeps operator proof expandable", () => {
  assert.match(appJs, /renderOperatorProofDetails/);
  assert.match(appJs, /Workflow Proof/);
  assert.match(appJs, /Worker Result/);
  assert.match(appJs, /operator-proof/);
  assert.match(appJs, /Payload audits/);
  assert.match(appJs, /Source pointers/);
  assert.match(indexHtml, /runtime-proof/);
});

test("chat MVP exposes async worker continuation controls without worker actions", () => {
  assert.match(appJs, /worker\.followup\.scheduled/);
  assert.match(appJs, /worker\.followup\.continue_requested/);
  assert.match(appJs, /worker\.followup\.cancelled/);
  assert.match(appJs, /worker\.followup\.dispatching/);
  assert.match(appJs, /worker\.followup\.completed/);
  assert.match(appJs, /worker\.followup\.blocked/);
  assert.match(appJs, /renderWorkerContinuationCard/);
  assert.match(appJs, /Leave As Async Follow-Up/);
  assert.match(appJs, /Approve \+ Run Official Read-Only/);
  assert.match(appJs, /Continue Status Check/);
  assert.match(appJs, /Cancel Follow-Up/);
  assert.match(appJs, /Cancelled follow-up is closed/);
  assert.match(appJs, /\/api\/worker-continuations/);
  assert.match(appJs, /workerContinuationId/);
  assert.match(appJs, /approvedDocumentCandidateId/);
  assert.match(appJs, /officialOpenClawUseCurrentTab/);
  assert.match(appJs, /officialOpenClawMultiPage/);
  assert.match(appJs, /Actions taken/);
  assert.match(appJs, /read_only_observation/);
});

test("chat MVP closes completed worker continuations and suppresses stale portal prompts", () => {
  assert.match(appJs, /hasCapturedPortalEvidence/);
  assert.match(appJs, /isSatisfiedByCapturedPortalEvidence/);
  assert.match(appJs, /portal_accounts/);
  assert.match(appJs, /upsertWorkerContinuationCard/);
  assert.match(appJs, /workerContinuationFromResult/);
  assert.match(appJs, /Completed follow-up is closed\. Source pointers and worker actions are shown in Worker Result\./);
  assert.match(appJs, /existing\.replaceWith\(next\)/);
});

test("chat MVP exposes multi-page worker proof fields", () => {
  assert.match(indexHtml, /Multi-page read-only worker/);
  assert.match(appJs, /officialOpenClawMultiPage\.checked = true/);
  assert.match(appJs, /Navigation plan/);
  assert.match(appJs, /evidence\.navigationPlan/);
  assert.match(appJs, /evidence\.discoveryReport/);
  assert.match(appJs, /SBC\/PDF/);
  assert.match(appJs, /documentCandidateCount/);
  assert.match(appJs, /approvedDocumentCandidate/);
  assert.match(appJs, /verifiedPageCount/);
  assert.match(appJs, /pageCount/);
  assert.match(appJs, /captured_official_openclaw_multi_page_read_only_observation/);
  assert.match(appJs, /evidenceChannelSummary/);
});

test("user-friendly MVP app is a separate auth plus chat surface wired to real APIs", () => {
  assert.match(indexHtml, /href="\/mvp"/);
  assert.match(mvpHtml, /Brainstyworkers Concierge MVP/);
  assert.match(mvpHtml, /id="startSession"/);
  assert.match(mvpHtml, /id="chatForm"/);
  assert.match(mvpHtml, /id="currentAnswer"/);
  assert.match(mvpHtml, /id="approvalPanel"/);
  assert.match(mvpHtml, /id="discoveryPanel"/);
  assert.match(mvpHtml, /id="sequence"/);
  assert.match(mvpHtml, /id="backendRoute"/);
  assert.match(mvpHtml, /id="facadeUrl"/);
  assert.match(mvpHtml, /Wefella FastAPI facade/);
  assert.match(mvpHtml, /Proof Dashboard/);
  assert.match(mvpHtml, /Use official OpenClaw/);
  assert.match(mvpHtml, /Multi-page read-only run/);
  assert.match(mvpHtml, /Live GPT decisioning/);
  assert.match(mvpJs, /\/api\/orchestrator\/auth-start/);
  assert.match(mvpJs, /\/api\/chat/);
  assert.match(mvpJs, /\/api\/auth\/local-session/);
  assert.match(mvpJs, /\/api\/chat\/stream/);
  assert.match(mvpJs, /facadeChatPayload/);
  assert.match(mvpJs, /streamFacadeTask/);
  assert.match(mvpJs, /pollFacadeTask/);
  assert.match(mvpJs, /routeApi/);
  assert.match(mvpJs, /startFacadeRuntimeEventStream/);
  assert.match(mvpJs, /\/api\/orchestrator\/approve/);
  assert.match(mvpJs, /\/api\/worker-continuations/);
  assert.match(mvpJs, /\/api\/document-candidates/);
  assert.match(mvpJs, /\/api\/document-candidates\/propose/);
  assert.match(mvpJs, /\/api\/openclaw\/official\/status/);
  assert.match(mvpJs, /\/api\/runtime\/events\/stream/);
  assert.match(mvpJs, /EventSource/);
  assert.match(mvpJs, /executeEvidenceObservation: false/);
  assert.match(mvpJs, /executeEvidenceObservation: true/);
  assert.match(mvpJs, /READ_ONLY_SCOPE/);
  assert.match(mvpJs, /approvalToken/);
  assert.match(mvpJs, /workerContinuationId/);
  assert.match(mvpJs, /READ_ONLY_DOCUMENT_SCOPE/);
  assert.match(mvpJs, /approvedDocumentCandidateId/);
  assert.match(mvpJs, /Prepare Approval/);
  assert.match(mvpJs, /Approve \+ Observe/);
  assert.match(mvpJs, /discoveryReport/);
  assert.match(mvpJs, /sourcePointers/);
  assert.match(mvpJs, /product_memory_retain/);
  assert.match(mvpCss, /grid-template-columns: minmax\(260px, 300px\) minmax\(420px, 1fr\) minmax\(280px, 360px\)/);
});
