import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { test } from "node:test";

const indexHtml = await readFile(new URL("../app/index.html", import.meta.url), "utf8");
const appJs = await readFile(new URL("../app/app.js", import.meta.url), "utf8");
const appCss = await readFile(new URL("../app/styles.css", import.meta.url), "utf8");
const mvpHtml = await readFile(new URL("../app/mvp.html", import.meta.url), "utf8");
const mvpJs = await readFile(new URL("../app/mvp.js", import.meta.url), "utf8");
const mvpCss = await readFile(new URL("../app/mvp.css", import.meta.url), "utf8");
const remoteBrowserHtml = await readFile(new URL("../app/remote-browser.html", import.meta.url), "utf8");
const remoteBrowserJs = await readFile(new URL("../app/remoteBrowser.js", import.meta.url), "utf8");
const browserStreamController = await readFile(new URL("../concierge/browserStreamController.mjs", import.meta.url), "utf8");
const mobilePackageJson = await readFile(new URL("../../apps/mobile-next/package.json", import.meta.url), "utf8");
const mobileNextConfig = await readFile(new URL("../../apps/mobile-next/next.config.mjs", import.meta.url), "utf8");
const mobilePage = await readFile(new URL("../../apps/mobile-next/app/page.jsx", import.meta.url), "utf8");
const mobileApi = await readFile(new URL("../../apps/mobile-next/lib/api.js", import.meta.url), "utf8");
const mobileCss = await readFile(new URL("../../apps/mobile-next/app/globals.css", import.meta.url), "utf8");
const serverMjs = await readFile(new URL("../server/server.mjs", import.meta.url), "utf8");
const projectOperatingSystem = await readFile(new URL("../../docs/PROJECT_OPERATING_SYSTEM.md", import.meta.url), "utf8");
const phaseScoreboard = await readFile(new URL("../../docs/PHASE_SCOREBOARD.md", import.meta.url), "utf8");
const nonMockedProofRules = await readFile(new URL("../../docs/NON_MOCKED_PROOF_RULES.md", import.meta.url), "utf8");
const continuousIntelligence = await readFile(new URL("../concierge/continuousIntelligence.mjs", import.meta.url), "utf8");

test("chat MVP surface exposes guided auth, portal readiness, and runtime timeline", () => {
  assert.match(indexHtml, /id="chatJourney"/);
  assert.match(indexHtml, /id="portalReady"/);
  assert.match(indexHtml, /id="officialOpenClawCurrentTab"/);
  assert.match(indexHtml, /id="officialOpenClawMultiPage"/);
  assert.match(indexHtml, /id="resetMvpJourney"/);
  assert.match(indexHtml, /id="replayMvpBenefits"/);
  assert.match(indexHtml, /id="answerPanel"/);
  assert.match(indexHtml, /id="runtimeTimeline"/);
  assert.match(indexHtml, /id="loadRuntimeEvents"/);
  assert.match(indexHtml, /id="liveWorkerGuide"/);
  assert.match(indexHtml, /id="checkLiveWorker"/);
  assert.match(indexHtml, /id="liveWorkerStatus"/);
  assert.match(indexHtml, /id="workerVersatility"/);
  assert.match(indexHtml, /Runtime Timeline/);
  assert.match(indexHtml, /Use official OpenClaw worker/);
  assert.match(indexHtml, /Use current OpenClaw tab/);
  assert.match(indexHtml, /Multi-page read-only worker/);
  assert.match(indexHtml, /Live Worker Readiness/);
  assert.match(indexHtml, /Replay Benefits MVP/);
});

test("chat MVP JavaScript requires sign-in and renders runtime graph events", () => {
  assert.match(appJs, /requireSignedInBeforeWorkflow/);
  assert.match(appJs, /\/api\/runtime\/events\?sessionId=/);
  assert.match(appJs, /EventSource/);
  assert.match(appJs, /workflow\.classified/);
  assert.match(appJs, /worker\.plan\.prepared/);
  assert.match(appJs, /approval\.recorded/);
  assert.match(appJs, /approval\.consumed/);
  assert.match(appJs, /worker\.status\.updated/);
  assert.match(appJs, /llmDecision\.mode/);
  assert.match(appJs, /renderWorkerOutcomeCard/);
  assert.match(appJs, /friendlyWorkerBlocker/);
  assert.match(appJs, /structuredBenefitSummary/);
  assert.match(appJs, /structuredClaimSummary/);
  assert.match(appJs, /Structured claims/);
  assert.match(appJs, /Discovery/);
  assert.match(appJs, /discoverySummary/);
  assert.match(appJs, /renderDocumentCandidateProof/);
  assert.match(appJs, /data-document-candidate-propose/);
  assert.match(appJs, /data-document-candidate-observe/);
  assert.match(appJs, /Evidence channels/);
  assert.match(appJs, /renderLiveWorkerGuide/);
  assert.match(appJs, /liveReadiness/);
  assert.match(appJs, /ready_for_read_only_approval/);
  assert.match(appJs, /auth_required/);
  assert.match(appJs, /auth_or_challenge_required/);
  assert.match(appJs, /portal_page_required/);
  assert.match(appJs, /Worker may try after approval/);
  assert.match(appJs, /Always blocked/);
  assert.match(appJs, /Fallback chain/);
});

test("chat MVP exposes repeatable benefits replay and final answer surface", () => {
  assert.match(appJs, /MVP_BENEFITS_MESSAGE/);
  assert.match(appJs, /resetMvpJourneySurface/);
  assert.match(appJs, /replayMvpBenefitsJourney/);
  assert.match(appJs, /productAuthenticate/);
  assert.match(appJs, /runProductChat\(MVP_BENEFITS_MESSAGE\)/);
  assert.match(appJs, /renderAnswerPanel/);
  assert.match(appJs, /Current Answer/);
  assert.match(appJs, /Latest LangGraph result for this session/);
  assert.match(appJs, /latest-answer-message/);
  assert.match(appJs, /memoryRetainSummary/);
  assert.match(appJs, /memoryNextAction/);
  assert.match(appJs, /data-answer-approve-readonly/);
  assert.match(appJs, /data-answer-worker-followup/);
  assert.match(appJs, /\/api\/orchestrator\/auth-start/);
  assert.match(appJs, /\/api\/chat/);
});

test("chat MVP keeps operator proof expandable", () => {
  assert.match(appJs, /renderOperatorProofDetails/);
  assert.match(appJs, /Workflow Proof/);
  assert.match(appJs, /Worker Result/);
  assert.match(appJs, /operator-proof/);
  assert.match(appJs, /Payload audits/);
  assert.match(appJs, /\/api\/audit/);
  assert.match(appJs, /renderAuditLog/);
  assert.match(indexHtml, /Audit Log/);
  assert.match(indexHtml, /Phase 10T/);
  assert.match(appJs, /Source pointers/);
  assert.match(indexHtml, /runtime-proof/);
  assert.match(appJs, /renderDynamicSkillProof/);
  assert.match(appJs, /dynamicSkillSelectedLine/);
  assert.match(appJs, /Dynamic Skills/);
  assert.match(appJs, /requiredOpenClawTasks/);
  assert.match(appJs, /generatorEditContract/);
  assert.match(appCss, /dynamic-skill-card/);
});

test("chat MVP exposes async worker continuation controls without worker actions", () => {
  assert.match(appJs, /worker\.followup\.scheduled/);
  assert.match(appJs, /worker\.followup\.continue_requested/);
  assert.match(appJs, /worker\.followup\.cancelled/);
  assert.match(appJs, /worker\.followup\.dispatching/);
  assert.match(appJs, /worker\.followup\.completed/);
  assert.match(appJs, /worker\.followup\.blocked/);
  assert.match(appJs, /renderWorkerContinuationCard/);
  assert.match(appJs, /Leave As Async Follow-Up/);
  assert.match(appJs, /Approve \+ Run Official Read-Only/);
  assert.match(appJs, /Continue Status Check/);
  assert.match(appJs, /Cancel Follow-Up/);
  assert.match(appJs, /Cancelled follow-up is closed/);
  assert.match(appJs, /\/api\/worker-continuations/);
  assert.match(appJs, /workerContinuationId/);
  assert.match(appJs, /approvedDocumentCandidateId/);
  assert.match(appJs, /officialOpenClawUseCurrentTab/);
  assert.match(appJs, /officialOpenClawMultiPage/);
  assert.match(appJs, /Actions taken/);
  assert.match(appJs, /read_only_observation/);
});

test("remote browser GUI exposes live view and human takeover controls", () => {
  assert.match(remoteBrowserHtml, /Worker browser — watch &amp; take over/);
  assert.match(remoteBrowserHtml, /mountRemoteBrowser/);
  assert.match(remoteBrowserHtml, /The assistant runs the portal read-only and never types your credentials/);
  assert.match(remoteBrowserJs, /\/api\/runtime\/browser\/frames\/stream/);
  assert.match(remoteBrowserJs, /\/api\/runtime\/browser\/screencast\/start/);
  assert.match(remoteBrowserJs, /\/api\/runtime\/browser\/takeover\/request/);
  assert.match(remoteBrowserJs, /\/api\/runtime\/browser\/takeover\/grant/);
  assert.match(remoteBrowserJs, /\/api\/runtime\/browser\/takeover\/input/);
  assert.match(remoteBrowserJs, /\/api\/runtime\/browser\/takeover\/end/);
  assert.match(remoteBrowserJs, /approvedBy: "user"/);
  assert.match(remoteBrowserJs, /placeholder="Tap the page, then type here \(password \/ captcha\)"/);
  assert.match(mvpHtml, /id="workerBrowserPanel"/);
  assert.match(mvpHtml, /id="remoteBrowserMount"/);
  assert.match(mvpJs, /mountWorkerBrowser/);
  assert.match(mvpJs, /targetUrl: elements\.portalUrl\.value\.trim\(\) \|\| null/);
  assert.match(mvpJs, /maybeHighlightWorkerBrowser/);
  assert.match(mvpJs, /The portal needs a login, 2FA, or captcha/);
});

test("chat MVP closes completed worker continuations and suppresses stale portal prompts", () => {
  assert.match(appJs, /hasCapturedPortalEvidence/);
  assert.match(appJs, /isSatisfiedByCapturedPortalEvidence/);
  assert.match(appJs, /portal_accounts/);
  assert.match(appJs, /upsertWorkerContinuationCard/);
  assert.match(appJs, /workerContinuationFromResult/);
  assert.match(appJs, /Completed follow-up is closed\. Source pointers and worker actions are shown in Worker Result\./);
  assert.match(appJs, /existing\.replaceWith\(next\)/);
});

test("chat MVP exposes multi-page worker proof fields", () => {
  assert.match(indexHtml, /Multi-page read-only worker/);
  assert.match(mvpHtml, /data-step="skill"/);
  assert.match(mvpJs, /renderDynamicSkillCard/);
  assert.match(mvpJs, /dynamicSkillContext/);
  assert.match(mvpJs, /requiredOpenClawTasks/);
  assert.match(mvpJs, /Success estimate/);
  assert.match(mvpCss, /dynamic-skill-panel/);
  assert.match(appJs, /officialOpenClawMultiPage\.checked = true/);
  assert.match(appJs, /Navigation plan/);
  assert.match(appJs, /evidence\.navigationPlan/);
  assert.match(appJs, /evidence\.discoveryReport/);
  assert.match(appJs, /SBC\/PDF/);
  assert.match(appJs, /documentCandidateCount/);
  assert.match(appJs, /approvedDocumentCandidate/);
  assert.match(appJs, /verifiedPageCount/);
  assert.match(appJs, /pageCount/);
  assert.match(appJs, /captured_official_openclaw_multi_page_read_only_observation/);
  assert.match(appJs, /evidenceChannelSummary/);
});

test("operator proof dashboard exposes Phase 10T research grounding, citation closure, graph, proposals, schedules, scheduler daemon, embeddings, and adaptive workers", () => {
  assert.match(indexHtml, /Phase 10T/);
  assert.match(indexHtml, /Operator Research Console/);
  assert.match(indexHtml, /id="researchStatus"/);
  assert.match(indexHtml, /id="researchConsole"/);
  assert.match(indexHtml, /id="operatorAssistantStatus"/);
  assert.match(indexHtml, /id="operatorAssistantConsole"/);
  assert.match(indexHtml, /id="operatorAssistantMessage"/);
  assert.match(indexHtml, /id="researchSourceUrl"/);
  assert.match(indexHtml, /id="researchSourceTitle"/);
  assert.match(indexHtml, /id="researchTopic"/);
  assert.match(indexHtml, /id="researchSearchQuery"/);
  assert.match(indexHtml, /id="researchAnswerToJudge"/);
  assert.match(indexHtml, /id="researchEmbeddingProvider"/);
  assert.match(indexHtml, /id="researchEmbeddingDimensions"/);
  assert.match(indexHtml, /id="researchBudgetDailyRuns"/);
  assert.match(indexHtml, /id="researchBudgetDailyCostCents"/);
  assert.match(indexHtml, /id="researchBudgetKillSwitch"/);
  assert.match(indexHtml, /id="researchBudgetKillSwitchReason"/);
  assert.match(indexHtml, /id="auditEventPrefix"/);
  assert.match(indexHtml, /id="loadResearchKpis"/);
  assert.match(indexHtml, /id="loadResearchAnalytics"/);
  assert.match(indexHtml, /id="loadResearchBudget"/);
  assert.match(indexHtml, /id="loadHandoffs"/);
  assert.match(indexHtml, /id="loadResearchWorker"/);
  assert.match(indexHtml, /id="loadResearchEmbeddings"/);
  assert.match(indexHtml, /id="reindexResearchEmbeddings"/);
  assert.match(indexHtml, /id="loadResearchGraph"/);
  assert.match(indexHtml, /id="buildResearchGraph"/);
  assert.match(indexHtml, /id="loadCitationClosure"/);
  assert.match(indexHtml, /id="loadResearchArtifacts"/);
  assert.match(indexHtml, /id="loadResearchEntities"/);
  assert.match(indexHtml, /id="loadResearchSources"/);
  assert.match(indexHtml, /id="loadResearchRuns"/);
  assert.match(indexHtml, /id="loadResearchSchedules"/);
  assert.match(indexHtml, /id="loadResearchSchedulerStatus"/);
  assert.match(indexHtml, /id="tickResearchSchedulerDaemon"/);
  assert.match(indexHtml, /id="tickResearchSchedules"/);
  assert.match(indexHtml, /id="loadAuditLog"/);
  assert.match(indexHtml, /id="startResearchRun"/);
  assert.match(indexHtml, /id="proposeResearchSource"/);
  assert.match(indexHtml, /id="chooseResearchEmbeddingRoute"/);
  assert.match(indexHtml, /id="saveResearchBudget"/);
  assert.match(indexHtml, /id="searchResearchEvidence"/);
  assert.match(indexHtml, /id="evaluateCitationClosure"/);
  assert.match(indexHtml, /id="loadOperatorTools"/);
  assert.match(indexHtml, /id="loadOperatorProposals"/);
  assert.match(indexHtml, /id="runOperatorAssistant"/);
  assert.match(appJs, /renderResearchConsole/);
  assert.match(appJs, /renderOperatorAssistantConsole/);
  assert.match(appJs, /\/api\/research\/kpis/);
  assert.match(appJs, /\/api\/research\/analytics/);
  assert.match(appJs, /\/api\/research\/budget/);
  assert.match(appJs, /\/api\/research\/review-queues/);
  assert.match(appJs, /\/api\/handoffs/);
  assert.match(appJs, /loadHumanHandoffs/);
  assert.match(appJs, /Human Handoff/);
  assert.match(appJs, /\/api\/research\/worker-status/);
  assert.match(appJs, /\/api\/research\/embeddings\/status/);
  assert.match(appJs, /\/api\/research\/embeddings\/route/);
  assert.match(appJs, /\/api\/research\/embeddings\/reindex/);
  assert.match(appJs, /\/api\/research\/graph/);
  assert.match(appJs, /\/api\/research\/graph\/build/);
  assert.match(appJs, /\/api\/research\/citation-closure/);
  assert.match(appJs, /\/api\/research\/citation-closure\/evaluate/);
  assert.match(appJs, /\/api\/research\/artifacts/);
  assert.match(appJs, /\/api\/research\/entities/);
  assert.match(appJs, /\/entities\/extract/);
  assert.match(appJs, /\/api\/research\/search/);
  assert.match(appJs, /\/api\/research\/sources/);
  assert.match(appJs, /\/api\/research\/runs/);
  assert.match(appJs, /\/api\/research\/schedules/);
  assert.match(appJs, /\/api\/operator\/tools/);
  assert.match(appJs, /\/api\/operator\/assistant/);
  assert.match(appJs, /\/api\/operator\/proposals/);
  assert.match(appJs, /data-research-source-approve/);
  assert.match(appJs, /data-research-source-reject/);
  assert.match(appJs, /data-research-run-source/);
  assert.match(appJs, /data-research-run-open/);
  assert.match(appJs, /data-research-run-cancel/);
  assert.match(appJs, /data-research-run-retry/);
  assert.match(appJs, /data-research-run-execute/);
  assert.match(appJs, /data-research-run-mock/);
  assert.match(appJs, /data-research-run-openclaw/);
  assert.match(appJs, /data-research-run-hermes/);
  assert.match(appJs, /approvedWorkerDispatch/);
  assert.match(appJs, /data-research-artifact-approve/);
  assert.match(appJs, /data-research-artifact-quarantine/);
  assert.match(appJs, /data-research-entities-extract/);
  assert.match(appJs, /data-operator-proposal-approve/);
  assert.match(appJs, /data-operator-proposal-reject/);
  assert.match(appJs, /executeResearchRun/);
  assert.match(appJs, /reviewResearchArtifact/);
  assert.match(appJs, /runOperatorAssistant/);
  assert.match(appJs, /decideOperatorProposal/);
  assert.match(appJs, /Trusted Evidence Search/);
  assert.match(appJs, /Research Evidence Graph/);
  assert.match(appJs, /Claim Citation Closure/);
  assert.match(appJs, /Research Entity Extraction/);
  assert.match(appJs, /Worker Status/);
  assert.match(appJs, /MockWorker/);
  assert.match(appJs, /researchConsole\.addEventListener\("click"/);
  assert.match(appJs, /operatorAssistantConsole\.addEventListener\("click"/);
  assert.match(appJs, /loadResearchKpis/);
  assert.match(appJs, /loadResearchAnalytics/);
  assert.match(appJs, /loadResearchBudget/);
  assert.match(appJs, /loadResearchReviewQueues/);
  assert.match(appJs, /saveResearchBudget/);
  assert.match(appJs, /loadResearchWorkerStatus/);
  assert.match(appJs, /loadResearchEmbeddingStatus/);
  assert.match(appJs, /chooseResearchEmbeddingRoute/);
  assert.match(appJs, /Research Budget And Kill Switch/);
  assert.match(appJs, /Expanded Review Queues/);
  assert.match(indexHtml, /id="loadResearchReviewQueues"/);
  assert.match(appJs, /reindexResearchEmbeddings/);
  assert.match(appJs, /loadResearchGraph/);
  assert.match(appJs, /buildResearchGraph/);
  assert.match(appJs, /loadCitationClosure/);
  assert.match(appJs, /evaluateCitationClosure/);
  assert.match(appJs, /loadResearchArtifacts/);
  assert.match(appJs, /loadResearchEntities/);
  assert.match(appJs, /extractResearchEntities/);
  assert.match(appJs, /searchResearchEvidence/);
  assert.match(appJs, /loadResearchSources/);
  assert.match(appJs, /loadResearchRuns/);
  assert.match(appJs, /loadResearchSchedules/);
  assert.match(appJs, /loadResearchSchedulerStatus/);
  assert.match(appJs, /tickResearchSchedulerDaemon/);
  assert.match(appJs, /tickResearchSchedules/);
  assert.match(appJs, /Scheduler Daemon/);
  assert.match(appJs, /loadAuditLog/);
  assert.match(appJs, /startResearchRun/);
  assert.match(appJs, /proposeResearchSource/);
  assert.match(appJs, /loadOperatorTools/);
  assert.match(appJs, /loadOperatorProposals/);
  assert.match(appCss, /research-grid/);
  assert.match(appCss, /operator-form-grid/);
  assert.match(appCss, /operator-assistant-form/);
  assert.match(appCss, /research-card/);
  assert.match(appCss, /research-artifact-list/);
});

test("server connector dashboard and Next mobile PWA expose only the v1 connector contract", () => {
  assert.match(indexHtml, /Server \+ Mobile Verification/);
  assert.match(indexHtml, /id="connectorProofStatus"/);
  assert.match(indexHtml, /id="loadConnectorProof"/);
  assert.match(indexHtml, /id="connectorProof"/);
  assert.match(appJs, /loadConnectorProof/);
  assert.match(appJs, /\/api\/proof\/runs\/server-connector-next-mobile-mvp/);
  assert.match(appJs, /renderConnectorProof/);
  assert.match(appCss, /connector-proof-grid/);
  assert.match(appCss, /connector-card/);
  assert.match(mobilePackageJson, /"next"/);
  assert.match(mobileNextConfig, /BRAINSTY_CONNECTOR_API_BASE/);
  assert.match(mobileNextConfig, /outputFileTracingRoot/);
  assert.match(mobilePage, /Brainstyworkers/);
  assert.match(mobilePage, /createBrowserSession/);
  assert.match(mobilePage, /TASK_FINAL_STATES/);
  assert.match(mobilePage, /userFacingAnswer/);
  assert.match(mobilePage, /Benefits answer ready/);
  assert.match(mobilePage, /connectBrowserStream/);
  assert.match(mobilePage, /parseSseChunk/);
  assert.match(mobilePage, /Live worker browser frame/);
  assert.match(mobilePage, /\/api\/v1 only/);
  assert.match(mobileApi, /Mobile client may only call \/api\/v1 endpoints/);
  assert.match(mobileApi, /NEXT_PUBLIC_BRAINSTY_CLIENT_API_BASE/);
  assert.match(mobileApi, /\/api\/v1\/sessions/);
  assert.match(mobileApi, /\/api\/v1\/tasks/);
  assert.match(mobileApi, /\/api\/v1\/openclaw\/readiness/);
  assert.match(mobileApi, /\/api\/v1\/browser\/sessions/);
  assert.doesNotMatch(mobileApi, /\/api\/chat/);
  assert.doesNotMatch(mobileApi, /\/api\/runtime\/browser/);
  assert.match(mobileCss, /mobile-shell/);
  assert.match(mobileCss, /step-strip/);
  assert.match(mobileCss, /answer-copy/);
  assert.match(mobileCss, /live-stage/);
  assert.match(browserStreamController, /captureScreenshotFallbackFrame/);
  assert.match(browserStreamController, /cdp_screenshot_fallback/);
  assert.match(browserStreamController, /lastFrame/);
});

test("Phase 32 canonical operating system is documented and visible in dashboard proof", () => {
  assert.match(projectOperatingSystem, /Source Of Truth Order/);
  assert.match(projectOperatingSystem, /Cortex wins/);
  assert.match(projectOperatingSystem, /No phase is done until both the worker repo changes and Cortex memory changes land on `main`/);
  assert.match(projectOperatingSystem, /Planner/);
  assert.match(projectOperatingSystem, /Verifier/);
  assert.match(projectOperatingSystem, /Cortex Scribe/);
  assert.match(projectOperatingSystem, /Phase 44 refines reviewer history audit exports into an operator-side history review surface/);

  assert.match(phaseScoreboard, /canonical_operating_system/);
  assert.match(phaseScoreboard, /continuous_procedural_memory/);
  assert.match(phaseScoreboard, /multi_channel_openclaw_gateway/);
  assert.match(phaseScoreboard, /production_database_rollout/);

  assert.match(nonMockedProofRules, /Do not call a stubbed LLM response an LLM proof/);
  assert.match(nonMockedProofRules, /Do not call a local fake provider final hosted-browser readiness/);
  assert.match(nonMockedProofRules, /Live LLM proof must/);
  assert.match(nonMockedProofRules, /Visual proof is required/);

  assert.match(serverMjs, /canonical_goal_tied_phase_execution/);
  assert.match(serverMjs, /canonical_phase_operating_system/);
  assert.match(serverMjs, /phase32_goal_tied_execution_contract_ready/);
  assert.match(serverMjs, /docs\/PROJECT_OPERATING_SYSTEM\.md/);
  assert.match(appJs, /renderConnectorProof/);
});

test("Phase 33 continuous intelligence shadow scaffold is documented and visible in dashboard proof", () => {
  assert.match(projectOperatingSystem, /Phase 44 refines reviewer history audit exports into an operator-side history review surface/);
  assert.match(projectOperatingSystem, /append-only shadow-run ledger/);
  assert.match(projectOperatingSystem, /case_state_shadow/);
  assert.match(projectOperatingSystem, /production decisioning still disabled/);

  assert.match(phaseScoreboard, /continuous_procedural_memory/);
  assert.match(phaseScoreboard, /Phase 44 reviewer history review refinement/);
  assert.match(phaseScoreboard, /brainstyworkers\.case_state\.v1/);
  assert.match(phaseScoreboard, /brainstyworkers\.pems\.v1/);
  assert.match(phaseScoreboard, /continuous_intelligence_shadow_runs/);
  assert.match(phaseScoreboard, /pems_candidate_maturity/);
  assert.match(phaseScoreboard, /pems_candidate_promotion_reviews/);
  assert.match(phaseScoreboard, /pems_candidate_evaluator_drafts/);
  assert.match(phaseScoreboard, /pems_candidate_claim_revisions/);
  assert.match(phaseScoreboard, /pems_candidate_review_followups/);
  assert.match(phaseScoreboard, /pems_candidate_review_history_exports/);

  assert.match(continuousIntelligence, /CASE_STATE_SCHEMA_VERSION = "brainstyworkers\.case_state\.v1"/);
  assert.match(continuousIntelligence, /PEMS_SCHEMA_VERSION = "brainstyworkers\.pems\.v1"/);
  assert.match(continuousIntelligence, /PEMS_PROMOTION_GATE_VERSION/);
  assert.match(continuousIntelligence, /PEMS_REVIEW_WORKBENCH_VERSION/);
  assert.match(continuousIntelligence, /PEMS_REVIEWER_COMPARISON_VERSION/);
  assert.match(continuousIntelligence, /PEMS_LIVE_EVALUATOR_FILTERING_VERSION/);
  assert.match(continuousIntelligence, /PEMS_LIVE_CLAIM_CITATION_CLOSURE_VERSION/);
  assert.match(continuousIntelligence, /PEMS_REVIEWER_CLAIM_REVISION_VERSION/);
  assert.match(continuousIntelligence, /PEMS_REVIEWER_FOLLOW_UP_VERSION/);
  assert.match(continuousIntelligence, /PEMS_REVIEWER_HISTORY_EXPORT_VERSION/);
  assert.match(continuousIntelligence, /evaluatePemsPromotionGate/);
  assert.match(continuousIntelligence, /createPemsEvaluatorDraft/);
  assert.match(continuousIntelligence, /createLiveGatedPemsEvaluatorDraft/);
  assert.match(continuousIntelligence, /buildPemsLiveEvaluatorFilteringProof/);
  assert.match(continuousIntelligence, /buildPemsLiveClaimCitationClosureProof/);
  assert.match(continuousIntelligence, /buildPemsReviewerClaimRevisionProof/);
  assert.match(continuousIntelligence, /recordPemsClaimRevision/);
  assert.match(continuousIntelligence, /buildPemsReviewerFollowUpProof/);
  assert.match(continuousIntelligence, /recordPemsReviewerFollowUp/);
  assert.match(continuousIntelligence, /buildPemsReviewerHistoryExportProof/);
  assert.match(continuousIntelligence, /recordPemsReviewerHistoryExport/);
  assert.match(continuousIntelligence, /buildPemsDraftClaimCitationClosure/);
  assert.match(continuousIntelligence, /buildPemsReviewerComparisonProvenance/);
  assert.match(continuousIntelligence, /UNIVERSAL_CASE_GATES/);
  assert.match(continuousIntelligence, /productionDrivingAllowed: false/);
  assert.match(continuousIntelligence, /shadow_only/);

  assert.match(serverMjs, /continuous_procedural_memory_shadow/);
  assert.match(serverMjs, /continuous_intelligence_shadow/);
  assert.match(serverMjs, /continuous_intelligence_shadow_persistence/);
  assert.match(serverMjs, /continuousIntelligencePersistence/);
  assert.match(serverMjs, /pems_supervised_promotion_gate/);
  assert.match(serverMjs, /pems_reviewer_evaluator_workbench/);
  assert.match(serverMjs, /pems_reviewer_ui/);
  assert.match(serverMjs, /pems_reviewer_comparison_provenance/);
  assert.match(serverMjs, /pems_live_evaluator_generation_filtering/);
  assert.match(serverMjs, /pems_live_claim_citation_closure/);
  assert.match(serverMjs, /pems_reviewer_claim_revisions/);
  assert.match(serverMjs, /pems_reviewer_follow_up_workflows/);
  assert.match(serverMjs, /pems_reviewer_history_audit_exports/);
  assert.match(serverMjs, /\/api\/continuous-intelligence\/pems\/promotion/);
  assert.match(serverMjs, /\/api\/continuous-intelligence\/pems\/reviews/);
  assert.match(serverMjs, /\/api\/continuous-intelligence\/pems\/workbench/);
  assert.match(serverMjs, /\/api\/continuous-intelligence\/pems\/evaluator-drafts/);
  assert.match(serverMjs, /\/api\/continuous-intelligence\/pems\/live-evaluator-drafts/);
  assert.match(serverMjs, /\/api\/continuous-intelligence\/pems\/claim-revisions/);
  assert.match(serverMjs, /\/api\/continuous-intelligence\/pems\/follow-ups/);
  assert.match(serverMjs, /\/api\/continuous-intelligence\/pems\/history-exports/);
  assert.match(serverMjs, /pemsTrusted/);
  assert.match(serverMjs, /productionDrivingAllowed/);
  assert.match(serverMjs, /continuousIntelligenceShadowOnly/);
  assert.match(serverMjs, /continuousIntelligencePersistenceOnly/);
  assert.match(serverMjs, /pemsReviewerWorkbenchAdvisoryOnly/);
  assert.match(serverMjs, /pemsReviewerUiRefOnly/);
  assert.match(serverMjs, /pemsReviewerComparisonRefOnly/);
});

test("Phase 44 PEMS reviewer UI exposes searchable history exports and snapshot comparison", () => {
  assert.match(indexHtml, /PEMS Reviewer Workbench/);
  assert.match(indexHtml, /Phase 44/);
  assert.match(indexHtml, /id="pemsWorkbench"/);
  assert.match(indexHtml, /id="loadPemsWorkbench"/);
  assert.match(indexHtml, /id="generatePemsLiveDraft"/);
  assert.match(indexHtml, /id="pemsDraftStatusFilter"/);
  assert.match(indexHtml, /id="pemsEvaluatorModeFilter"/);
  assert.match(indexHtml, /id="pemsLiveOnlyFilter"/);
  assert.match(indexHtml, /id="pemsHistoryFollowupFilter"/);
  assert.match(indexHtml, /id="pemsHistoryExportRefFilter"/);
  assert.match(indexHtml, /id="pemsHistorySnapshotHashFilter"/);
  assert.match(indexHtml, /id="pemsHistorySortBy"/);
  assert.match(indexHtml, /id="pemsHistorySortDirection"/);
  assert.match(indexHtml, /id="pemsReviewRationale"/);
  assert.match(indexHtml, /id="pemsClaimRevisionText"/);
  assert.match(indexHtml, /id="recordPemsClaimRevision"/);
  assert.match(indexHtml, /id="pemsFollowUpRationale"/);
  assert.match(indexHtml, /id="recordPemsFollowUp"/);
  assert.match(indexHtml, /id="pemsHistoryExportReason"/);
  assert.match(indexHtml, /id="recordPemsHistoryExport"/);
  assert.match(indexHtml, /data-pems-review-action="approved"/);
  assert.match(indexHtml, /data-pems-review-action="rejected"/);
  assert.match(indexHtml, /data-pems-review-action="blocked"/);

  assert.match(appJs, /loadPemsWorkbench/);
  assert.match(appJs, /renderPemsWorkbench/);
  assert.match(appJs, /currentPemsWorkbenchQuery/);
  assert.match(appJs, /renderPemsDraftQueue/);
  assert.match(appJs, /generatePemsLiveEvaluatorDraft/);
  assert.match(appJs, /submitPemsWorkbenchReview/);
  assert.match(appJs, /submitPemsClaimRevision/);
  assert.match(appJs, /submitPemsReviewerFollowUp/);
  assert.match(appJs, /submitPemsReviewerHistoryExport/);
  assert.match(appJs, /\/api\/continuous-intelligence\/pems\/workbench/);
  assert.match(appJs, /\/api\/continuous-intelligence\/pems\/live-evaluator-drafts/);
  assert.match(appJs, /\/api\/continuous-intelligence\/pems\/claim-revisions/);
  assert.match(appJs, /\/api\/continuous-intelligence\/pems\/follow-ups/);
  assert.match(appJs, /\/api\/continuous-intelligence\/pems\/history-exports/);
  assert.match(appJs, /\/api\/continuous-intelligence\/pems\/reviews/);
  assert.match(appJs, /Phase 44 Reviewer History Review Refinement/);
  assert.match(appJs, /Reviewer History Audit Export/);
  assert.match(appJs, /Reviewer History Search And Snapshot Diff/);
  assert.match(appJs, /Claim Citation Closure/);
  assert.match(appJs, /renderPemsClaimCitationClosure/);
  assert.match(appJs, /renderPemsClaimRevision/);
  assert.match(appJs, /renderPemsReviewerFollowUp/);
  assert.match(appJs, /renderPemsReviewerHistoryExport/);
  assert.match(appJs, /renderPemsReviewerHistoryReview/);
  assert.match(appJs, /pemsClaimClosureVetoed/);
  assert.match(appJs, /pemsClaimRevisionResolved/);
  assert.match(appJs, /firstEditablePemsClaim/);
  assert.match(appJs, /Claim citation closure requires reviewer edits before approval/);
  assert.match(appJs, /liveClaimCitationClosure/);
  assert.match(appJs, /reviewerClaimRevisions/);
  assert.match(appJs, /reviewerFollowUps/);
  assert.match(appJs, /reviewerHistoryExports/);
  assert.match(appJs, /reviewerHistoryReview/);
  assert.match(appJs, /Underlying UI gate/);
  assert.match(appJs, /Phase 39 gate/);
  assert.match(appJs, /Comparison gate/);
  assert.match(appJs, /Underlying workbench/);
  assert.match(appJs, /Reviewer Filters/);
  assert.match(appJs, /Deterministic Vs Advisory Comparison/);
  assert.match(appJs, /Evaluator Provenance/);
  assert.match(appJs, /liveProofClaimed/);
  assert.match(appJs, /Mocked output proof/);
  assert.match(appJs, /advisoryDraftId/);
  assert.match(appJs, /rawAdvisoryNoteStored/);
  assert.match(appJs, /rawConsistencyTraceStored/);
  assert.match(appJs, /productionDrivingAllowed: false/);
  assert.match(appJs, /human reviewer \+ deterministic validator/);
  assert.match(serverMjs, /reviewerUi: buildPemsReviewerUiProof/);
  assert.match(serverMjs, /phase37_pems_reviewer_ui_ready/);
  assert.match(serverMjs, /ref_only_operator_review_ui/);
  assert.match(serverMjs, /pems_reviewer_ui/);
  assert.match(serverMjs, /reviewerComparison: buildPemsReviewerComparisonProof/);
  assert.match(serverMjs, /liveEvaluatorFiltering: buildPemsLiveEvaluatorProof/);
  assert.match(serverMjs, /liveClaimCitationClosure: buildPemsClaimCitationClosureProof/);
  assert.match(serverMjs, /reviewerClaimRevisions: buildPemsClaimRevisionProof/);
  assert.match(serverMjs, /reviewerFollowUps: buildPemsReviewerFollowUpWorkflowProof/);
  assert.match(serverMjs, /reviewerHistoryExports: buildPemsReviewerHistoryAuditExportProof/);
  assert.match(serverMjs, /reviewerHistoryReview: buildPemsReviewerHistoryReviewRefinementProof/);
  assert.match(continuousIntelligence, /phase38_reviewer_comparison_provenance_ready/);
  assert.match(continuousIntelligence, /phase39_live_evaluator_filtering_ready/);
  assert.match(continuousIntelligence, /phase40_claim_citation_closure_veto_visible/);
  assert.match(continuousIntelligence, /phase41_reviewer_claim_revision_ready/);
  assert.match(continuousIntelligence, /phase42_reviewer_follow_up_workflow_ready/);
  assert.match(continuousIntelligence, /phase43_reviewer_history_audit_export_ready/);
  assert.match(continuousIntelligence, /phase44_reviewer_history_review_refinement_ready/);
  assert.match(continuousIntelligence, /mockedLlmOutputCountsAsProof: false/);
  assert.match(serverMjs, /pems_reviewer_comparison_provenance/);
  assert.match(serverMjs, /pems_live_evaluator_generation_filtering/);
  assert.match(serverMjs, /pems_live_claim_citation_closure/);
  assert.match(serverMjs, /pems_reviewer_claim_revisions/);
  assert.match(serverMjs, /pems_reviewer_follow_up_workflows/);
  assert.match(serverMjs, /pems_reviewer_history_audit_exports/);
  assert.match(serverMjs, /pems_reviewer_history_review_refinement/);

  assert.match(appCss, /pems-workbench-grid/);
  assert.match(appCss, /pems-filter-bar/);
  assert.match(appCss, /pems-draft-queue/);
  assert.match(appCss, /pems-comparison-table/);
  assert.match(appCss, /pems-claim-closure-table/);
  assert.match(appCss, /pems-revision-diff/);
  assert.match(appCss, /pems-followup-chain/);
  assert.match(appCss, /pems-history-export/);
  assert.match(appCss, /pems-history-review/);
  assert.match(appCss, /pems-evidence-chips/);
  assert.match(appCss, /pems-review-form/);
  assert.match(appCss, /pems-review-actions/);
});

test("user-friendly MVP app is a separate auth plus chat surface wired to real APIs", () => {
  assert.match(indexHtml, /href="\/mvp"/);
  assert.match(mvpHtml, /Brainstyworkers Concierge MVP/);
  assert.match(mvpHtml, /id="startSession"/);
  assert.match(mvpHtml, /id="chatForm"/);
  assert.match(mvpHtml, /id="currentAnswer"/);
  assert.match(mvpHtml, /class="mode-switch"/);
  assert.match(mvpHtml, /data-ui-mode="chat"/);
  assert.match(mvpHtml, /data-ui-mode="split"/);
  assert.match(mvpHtml, /data-ui-mode="guided"/);
  assert.match(mvpHtml, /data-ui-mode="bento"/);
  assert.match(mvpHtml, /id="approvalPanel"/);
  assert.match(mvpHtml, /id="historyPanel"/);
  assert.match(mvpHtml, /id="handoffPanel"/);
  assert.match(mvpHtml, /id="loadHandoffs"/);
  assert.match(mvpHtml, /id="feedbackComment"/);
  assert.match(mvpHtml, /id="loadHistory"/);
  assert.match(mvpHtml, /id="exportSession"/);
  assert.match(mvpHtml, /id="submitUsefulFeedback"/);
  assert.match(mvpHtml, /id="submitNeedsFollowupFeedback"/);
  assert.match(mvpHtml, /id="discoveryPanel"/);
  assert.match(mvpHtml, /id="sequence"/);
  assert.match(mvpHtml, /id="backendRoute"/);
  assert.match(mvpHtml, /id="facadeUrl"/);
  assert.match(mvpHtml, /<option value="wefella" selected>Wefella FastAPI facade<\/option>/);
  assert.match(mvpHtml, /Node \/ LangGraph runtime \(operator parity\)/);
  assert.match(mvpHtml, /id="runParity"/);
  assert.match(mvpHtml, /id="parityPanel"/);
  assert.match(mvpHtml, /id="phase9fPanel"/);
  assert.match(mvpHtml, /id="documentFile"/);
  assert.match(mvpHtml, /id="documentKind"/);
  assert.match(mvpHtml, /id="uploadDocument"/);
  assert.match(mvpHtml, /id="askUploadedDocument"/);
  assert.match(mvpHtml, /id="uploadPanel"/);
  assert.match(mvpHtml, /Upload \+ Extract/);
  assert.match(mvpHtml, /Ask About Upload/);
  assert.match(mvpHtml, /Compare Benefits Route/);
  assert.match(mvpHtml, /Trusted Research Answers/);
  assert.match(mvpHtml, /Wefella FastAPI facade/);
  assert.match(mvpHtml, /Proof Dashboard/);
  assert.match(mvpHtml, /Use official OpenClaw/);
  assert.match(mvpHtml, /Multi-page read-only run/);
  assert.match(mvpHtml, /Live GPT decisioning/);
  assert.match(mvpJs, /\/api\/orchestrator\/auth-start/);
  assert.match(mvpJs, /\/api\/chat/);
  assert.match(mvpJs, /\/api\/auth\/local-session/);
  assert.match(mvpJs, /isFacadeUnavailableError/);
  assert.match(mvpJs, /FastAPI facade unavailable; using same-origin Node \/ LangGraph runtime/);
  assert.match(mvpJs, /facade_unavailable/);
  assert.match(mvpJs, /FastAPI facade unavailable; use Node \/ LangGraph runtime for local MVP testing/);
  assert.match(mvpJs, /\/api\/chat\/stream/);
  assert.match(mvpJs, /facadeChatPayload/);
  assert.match(mvpJs, /streamFacadeTask/);
  assert.match(mvpJs, /pollFacadeTask/);
  assert.match(mvpJs, /return elements\.backendRoute\?\.value \?\? "wefella"/);
  assert.match(mvpJs, /runParityCheck/);
  assert.match(mvpJs, /runNodeParity/);
  assert.match(mvpJs, /runFacadeParity/);
  assert.match(mvpJs, /compareParityRuns/);
  assert.match(mvpJs, /mvp_phase9d_node_parity/);
  assert.match(mvpJs, /mvp_phase9d_fastapi_parity/);
  assert.match(mvpJs, /No evidence observation or worker action was approved/);
  assert.match(mvpJs, /routeApi/);
  assert.match(mvpJs, /startFacadeRuntimeEventStream/);
  assert.match(mvpJs, /\/api\/orchestrator\/approve/);
  assert.match(mvpJs, /\/api\/worker-continuations/);
  assert.match(mvpJs, /\/api\/document-candidates/);
  assert.match(mvpJs, /\/api\/document-candidates\/propose/);
  assert.match(mvpJs, /\/api\/uploads/);
  assert.match(mvpJs, /\/api\/sessions\/\$\{encodeURIComponent\(state\.session\.id\)\}/);
  assert.match(mvpJs, /\/api\/feedback/);
  assert.match(mvpJs, /\/api\/handoffs/);
  assert.match(mvpJs, /api\("\/api\/openclaw\/official\/status"/);
  assert.match(remoteBrowserJs, /\/api\/runtime\/browser\/screencast\/start/);
  assert.match(remoteBrowserJs, /targetUrl/);
  assert.match(mvpJs, /humanHandoff/);
  assert.match(mvpJs, /Human Handoff/);
  assert.match(mvpJs, /loadSessionHistory/);
  assert.match(mvpJs, /submitFeedback/);
  assert.match(mvpJs, /exportSessionAnswer/);
  assert.match(mvpJs, /downloadTextFile/);
  assert.match(mvpJs, /contentHash/);
  assert.match(mvpJs, /uploadDocument/);
  assert.match(mvpJs, /askAboutUploadedDocument/);
  assert.match(mvpJs, /uploaded_document_ids/);
  assert.match(mvpJs, /uploadedDocumentIds/);
  assert.match(mvpJs, /facade_required/);
  assert.match(mvpJs, /document_file_required/);
  assert.match(mvpJs, /uploaded_document_required/);
  assert.match(mvpJs, /readFileAsDataUrl/);
  assert.match(mvpJs, /safe_text_preview/);
  assert.match(mvpJs, /\/api\/openclaw\/official\/status/);
  assert.match(mvpJs, /\/api\/runtime\/events\/stream/);
  assert.match(mvpJs, /EventSource/);
  assert.match(mvpJs, /executeEvidenceObservation: false/);
  assert.match(mvpJs, /executeEvidenceObservation: true/);
  assert.match(mvpJs, /READ_ONLY_SCOPE/);
  assert.match(mvpJs, /approvalToken/);
  assert.match(mvpJs, /workerContinuationId/);
  assert.match(mvpJs, /READ_ONLY_DOCUMENT_SCOPE/);
  assert.match(mvpJs, /approvedDocumentCandidateId/);
  assert.match(mvpJs, /Prepare Approval/);
  assert.match(mvpJs, /Approve \+ Observe/);
  assert.match(mvpJs, /discoveryReport/);
  assert.match(mvpJs, /sourcePointers/);
  assert.match(mvpJs, /renderCitationDetails/);
  assert.match(mvpJs, /renderCitationCard/);
  assert.match(mvpJs, /renderMemoryDetails/);
  assert.match(mvpJs, /AI2UI_BLOCK_CONTRACT_VERSION/);
  assert.match(mvpJs, /AI2UI_MODE_BLOCKS/);
  assert.match(mvpJs, /setUiMode/);
  assert.match(mvpJs, /localStorage\.setItem\("brainstyworkers\.mvp\.uiMode"/);
  assert.match(mvpJs, /ai2uiBlocks/);
  assert.match(mvpJs, /renderAi2UiBlocks/);
  assert.match(mvpJs, /renderUnknownAi2UiBlock/);
  assert.match(mvpJs, /Unsupported UI block/);
  assert.match(mvpJs, /uploaded_document_context/);
  assert.match(mvpJs, /Source details/);
  assert.match(mvpJs, /Graphiti retain\/recall/);
  assert.match(mvpJs, /product_memory_retain/);
  assert.match(mvpCss, /citation-panel/);
  assert.match(mvpCss, /citation-card/);
  assert.match(mvpCss, /memory-panel/);
  assert.match(mvpCss, /mode-switch/);
  assert.match(mvpCss, /ai2ui-block-grid/);
  assert.match(mvpCss, /body\[data-ui-mode="chat"\]/);
  assert.match(mvpCss, /body\[data-ui-mode="guided"\]/);
  assert.match(mvpCss, /body\[data-ui-mode="bento"\]/);
  assert.match(mvpCss, /citation-spans/);
  assert.match(mvpJs, /renderPhase9FProof/);
  assert.match(mvpJs, /phase9FStatus/);
  assert.match(mvpJs, /operatorDashboardUrl/);
  assert.match(mvpJs, /precise_blocker/);
  assert.match(mvpJs, /Open operator proof for this session/);
  assert.match(mvpCss, /grid-template-columns: minmax\(260px, 300px\) minmax\(420px, 1fr\) minmax\(280px, 360px\)/);
  assert.match(mvpCss, /parity-grid/);
  assert.match(mvpCss, /parity-row\.mismatch/);
  assert.match(mvpCss, /phase-proof-state\.sourced_result/);
  assert.match(mvpCss, /upload-panel/);
  assert.match(mvpCss, /upload-field/);
  assert.match(mvpCss, /continuity-panel/);
  assert.match(mvpCss, /history-panel/);
  assert.match(mvpCss, /history-message/);
  assert.match(appJs, /hydrateOperatorFromQuery/);
  assert.match(appJs, /new URLSearchParams\(window\.location\.search\)/);
});
